#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Generate the board's advisor agents from a knowledge repo.

Reads ``roster.yaml`` from the knowledge root and writes, per advisor:

* ``<out>/agents/board-<slug>.md`` -- the subagent, from ``templates/advisor.md.tmpl``
* ``<out>/skills/ask-<slug>/SKILL.md`` -- the ``/ask-<slug>`` entry point,
  from ``templates/ask.md.tmpl``

Both are build artifacts (skill-design.md 3.2). Previously generated files whose
slug has left the roster are removed; files without the generated marker are
never touched.

Knowledge root resolution, first match wins (skill-design.md 3.5):

1. ``--knowledge PATH``
2. ``BOARD_KNOWLEDGE``
3. ``knowledge`` in ``$XDG_CONFIG_HOME/board/config.toml`` (default ``~/.config``)
4. ``./knowledge``

Run: ``uv run scripts/generate-agents.py [--knowledge PATH] [--out DIR] [--dry-run]``
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import tomllib
import yaml

REPO = Path(__file__).resolve().parent.parent
AGENT_TEMPLATE = REPO / "templates" / "advisor.md.tmpl"
ASK_TEMPLATE = REPO / "templates" / "ask.md.tmpl"
MARKER = "GENERATED by board/scripts/generate-agents.py"
SLUG = re.compile(r"^[a-z][a-z0-9-]*$")
SECTION = re.compile(r"^## (\d+)\.", re.MULTILINE)
PLACEHOLDER = re.compile(r"\{\{(\w+)\}\}")
# Wiki sections by mode (skill-design.md 2.1). Method drops only 6 and 7;
# counsel reads them at runtime. 9 is the source map, an index, not persona.
VOICE_SECTIONS = (6, 7)
REQUIRED_SECTIONS = tuple(range(1, 10))


class BoardError(Exception):
    """A problem with the knowledge repo or roster that the user must fix."""


@dataclass(frozen=True)
class Advisor:
    slug: str
    name: str
    wiki: str
    raw: str
    job: str


@dataclass(frozen=True)
class Roster:
    owner: str  # whose board this is, as advisors address them
    context: str  # standing-context file, relative to the knowledge root
    advisors: list[Advisor]


@dataclass(frozen=True)
class SplitWiki:
    core: str
    voice_offset: int  # 1-indexed first line of section 6, for the Read tool
    voice_limit: int  # line count of sections 6-7
    sha256: str


# --- knowledge root ---------------------------------------------------------


def config_path() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "board" / "config.toml"


def resolve_knowledge(flag: str | None) -> tuple[Path, str]:
    """Return the knowledge root and a label naming which rule chose it."""
    if flag:
        return Path(flag).expanduser().resolve(), "--knowledge"
    env = os.environ.get("BOARD_KNOWLEDGE")
    if env:
        return Path(env).expanduser().resolve(), "BOARD_KNOWLEDGE"
    cfg = config_path()
    if cfg.is_file():
        with cfg.open("rb") as fh:
            data = tomllib.load(fh)
        value = data.get("board", {}).get("knowledge")
        if value:
            return Path(value).expanduser().resolve(), str(cfg)
    return (Path.cwd() / "knowledge").resolve(), "./knowledge"


# --- roster and wikis -------------------------------------------------------


def load_roster(root: Path) -> Roster:
    path = root / "roster.yaml"
    if not path.is_file():
        raise BoardError(f"no roster.yaml in knowledge root {root}")
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    owner, context = (str(data.get(k) or "").strip() for k in ("owner", "context"))
    if not owner or not context:
        raise BoardError(f"{path}: top-level 'owner' and 'context' are required")
    if not (root / context).is_file():
        raise BoardError(f"{path}: context file not found at {root / context}; every advisor loads it")
    entries = data.get("advisors")
    if not isinstance(entries, list) or not entries:
        raise BoardError(f"{path}: expected a non-empty 'advisors' list")

    advisors: list[Advisor] = []
    seen: set[str] = set()
    for i, entry in enumerate(entries):
        missing = [k for k in ("slug", "name", "wiki", "raw", "job") if not entry.get(k)]
        if missing:
            raise BoardError(f"{path}: advisor #{i + 1} missing {', '.join(missing)}")
        advisor = Advisor(**{k: str(entry[k]).strip() for k in ("slug", "name", "wiki", "raw", "job")})
        if not SLUG.match(advisor.slug):
            raise BoardError(f"{path}: slug {advisor.slug!r} must match {SLUG.pattern}")
        if advisor.slug in seen:
            raise BoardError(f"{path}: duplicate slug {advisor.slug!r}")
        seen.add(advisor.slug)
        for field in ("wiki", "raw"):
            target = root / getattr(advisor, field)
            if not (target.is_file() if field == "wiki" else target.is_dir()):
                raise BoardError(f"{path}: {advisor.slug}.{field} not found at {target}")
        advisors.append(advisor)
    return Roster(owner, context, advisors)


def split_wiki(path: Path) -> SplitWiki:
    """Split a nine-section wiki into the always-loaded core and the voice range."""
    text = path.read_text(encoding="utf-8")
    heads = {int(m.group(1)): m.start() for m in SECTION.finditer(text)}
    absent = [n for n in REQUIRED_SECTIONS if n not in heads]
    if absent:
        raise BoardError(f"{path}: missing section(s) {', '.join(map(str, absent))}")

    voice_start, voice_end = heads[VOICE_SECTIONS[0]], heads[VOICE_SECTIONS[-1] + 1]
    # Drop the wiki's own H1: the template supplies the heading.
    core_head = re.sub(r"\A# .*\n+", "", text[:voice_start])
    core = (core_head + text[voice_end:]).strip()
    offset = text.count("\n", 0, voice_start) + 1
    limit = text.count("\n", voice_start, voice_end)
    return SplitWiki(core, offset, limit, hashlib.sha256(text.encode()).hexdigest()[:16])


# --- rendering --------------------------------------------------------------


def render(template: str, values: dict[str, str]) -> str:
    def sub(m: re.Match[str]) -> str:
        key = m.group(1)
        if key not in values:
            raise BoardError(f"template placeholder {{{{{key}}}}} has no value")
        return values[key]

    return PLACEHOLDER.sub(sub, template)


def build(root: Path, roster: Roster) -> dict[str, str]:
    """Return {path relative to out dir: content} for every generated file."""
    agent_tmpl = AGENT_TEMPLATE.read_text(encoding="utf-8")
    ask_tmpl = ASK_TEMPLATE.read_text(encoding="utf-8")
    files: dict[str, str] = {}
    for a in roster.advisors:
        wiki = split_wiki(root / a.wiki)
        values = {
            "slug": a.slug,
            "name": a.name,
            "job": " ".join(a.job.split()).replace('"', "'"),
            "owner": roster.owner,
            "knowledge": str(root),
            "context_abs": str(root / roster.context),
            "wiki_rel": a.wiki,
            "wiki_abs": str(root / a.wiki),
            "raw_abs": str(root / a.raw),
            "wiki_sha": wiki.sha256,
            "voice_offset": str(wiki.voice_offset),
            "voice_limit": str(wiki.voice_limit),
            "core": wiki.core,
        }
        files[f"agents/board-{a.slug}.md"] = render(agent_tmpl, values)
        files[f"skills/ask-{a.slug}/SKILL.md"] = render(ask_tmpl, values)
    return files


def stale(out: Path, keep: set[str]) -> list[Path]:
    """Generated files in ``out`` whose advisor is no longer in the roster."""
    candidates = [*out.glob("agents/board-*.md"), *out.glob("skills/ask-*/SKILL.md")]
    return sorted(
        p for p in candidates if str(p.relative_to(out)) not in keep and MARKER in p.read_text(encoding="utf-8")
    )


# --- entry point ------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the board's advisor agents from a knowledge repo.")
    parser.add_argument("--knowledge", help="knowledge repo root (overrides env and config)")
    parser.add_argument(
        "--out",
        default=str(Path.home() / ".claude"),
        help="Claude Code config dir to write into (default: ~/.claude)",
    )
    parser.add_argument("--dry-run", action="store_true", help="print what would change, write nothing")
    args = parser.parse_args(argv)

    try:
        root, source = resolve_knowledge(args.knowledge)
        if not root.is_dir():
            raise BoardError(f"knowledge root {root} (from {source}) does not exist")
        files = build(root, load_roster(root))
    except BoardError as exc:
        print(f"board: {exc}", file=sys.stderr)
        return 1

    out = Path(args.out).expanduser()
    print(f"knowledge: {root}  (from {source})")
    current_by_rel = {rel: (out / rel).read_text(encoding="utf-8") if (out / rel).is_file() else None for rel in files}
    foreign = [out / rel for rel, cur in current_by_rel.items() if cur is not None and MARKER not in cur]
    if foreign:
        for path in foreign:
            print(f"board: refusing to overwrite hand-authored {path}", file=sys.stderr)
        return 1
    for rel, content in files.items():
        path = out / rel
        current = current_by_rel[rel]
        state = "unchanged" if current == content else ("updated" if current else "created")
        print(f"  {state:9} {path}")
        if state != "unchanged" and not args.dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    for path in stale(out, set(files)):
        print(f"  {'removed':9} {path}")
        if not args.dry_run:
            path.unlink()
            if path.name == "SKILL.md" and not any(path.parent.iterdir()):
                path.parent.rmdir()
    return 0


if __name__ == "__main__":
    sys.exit(main())
